# Generated by Django 3.0.1 on 2019-12-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_gift_gifturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftslist',
            name='owner',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='giftslist',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='giftslist',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='giftslist',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
