# Generated by Django 3.0.1 on 2020-01-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_auto_20200105_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftslist',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
