# Generated by Django 3.0.1 on 2020-01-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0006_auto_20200111_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='gift_list',
            new_name='gifts_list',
        ),
    ]
